name: Deploy MoneyApp Backend to SmarterASP

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Tải code từ GitHub về máy ảo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cài đặt môi trường .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    # 3. Khôi phục các thư viện
    - name: Restore dependencies
      run: dotnet restore

    # 4. Build và đóng gói (Publish) code ra thư mục publish_output
    - name: Publish code
      run: dotnet publish SE114-MoneyApp-BE/SE114-MoneyApp-BE.csproj -c Release -o ./publish_output

    - name: Take app offline
      run: |
        echo "API is updating..." > app_offline.htm
        # Cập nhật lại đường dẫn curl cho đích danh file
        curl -T app_offline.htm ftp://${{ secrets.FTP_SERVER }}/se114-moneyapp/app_offline.htm --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"
        echo "Đã đưa app_offline.htm lên server. Bắt đầu đếm ngược 15 giây chờ IIS nhả file..."
        sleep 15

    # 5. Dùng FTP đồng bộ thẳng file đã build lên thư mục SmarterASP
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish_output/
        server-dir: /se114-moneyapp/
        
    - name: Bring app online
      run: |
        curl -Q "-DELE /se114-moneyapp/app_offline.htm" ftp://${{ secrets.FTP_SERVER }}/ --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"
      continue-on-error: true
